### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Honos2014** [GuruSR/Watchy_GSR#10]
Hello there,
I am confused with the instruction for compilation.
I am a newbie with platfomrio and ESP32.

So I cloned the git 'cd' into it and try:
pio run
and get:
.pio/build/watchy/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `setup()'
.pio/build/watchy/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0xc): undefined reference to `loop()'
.pio/build/watchy/libFrameworkArduino.a(main.cpp.o): in function `loopTask(void*)'

collect2: error: ld returned 1 exit status
*** [.pio/build/watchy/firmware.elf] Error 1

I surely missed something.
Can you shed some light on this please. It will really be appreciated.

**Comment by GuruSR** [comment]
I'm not 100% familiar with PlatformIO, but I would verify that PlatformIO is up to date and so is the required Python.

**Comment by Honos2014** [comment]
Thank you for the reply.
I really hope I'll be able to use watchy_gsr it looks prromising.

**Comment by GuruSR** [comment]
You can also try using the Discord mentioned at watchy.sqfmi.com to talk to people for help on compiling, I also frequent that as well.
