### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lidense** [GuruSR/Watchy_GSR#17]
I am trying to compile with Platformio but I get this error message:
VCSBaseException: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', 'v2.2', 'https://github.com/GuruSR/SmallRTC.git', '/home/mbantu/.platformio/.cache/tmp/pkg-installing-5rya822i']

**Comment by GuruSR** [comment]
Not sure where that is getting the v2.2 branch from, if the git folder locally isn't clean, it'll remember the old tags, you should remove the existing SmallRTC repository locally on your computer, then try this again.  I've seen the git folder list the v2.2 tag but once I cleaned the SmallRTC folder out and re-cloned the repository, the v2.2 tag is gone as it should be.
