### ISSUE TITLE
Totaly new...

### ISSUE THREAD

**Issue by KostasDaskalos** [GuruSR/Watchy_GSR#2]
This is not an ...issue per se for the provided code it is a ...totally new user question. I know I should not ask this kind of questions but I have been gifted this amazing smartwatch ( Watchy-SQFMI ) and I am lost... How do I upload your code to the watch? I do not know where to find ( although I searched... ) an "OTA uploading tool"!
[Edit]
I know I am doing something wrong because when I try to upload the code via Arduino IDE I got this message and it stops:

`WARNING: library Rtc_Pcf8563 claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
c:\Users\Kostas\Documents\Arduino\libraries\Watchy_GSR\Watchy_GSR.cpp: In member function 'void WatchyGSR::DisplayInit(bool)':
c:\Users\Kostas\Documents\Arduino\libraries\Watchy_GSR\Watchy_GSR.cpp:3303:16: error: 'class GxEPD2_154_D67' has no member named 'setDarkBorder'
   display.epd2.setDarkBorder(Options.Border | ForceDark);
                ^~~~~~~~~~~~~
Compilation error: exit status 1}`

Following the instructions to the letter...

**Comment by GuruSR** [comment]
Read the Compilation Instructions in the src folder, and edit the libraries for it, there are 2.

In some versions of the Watchy, the menu for "Setup WiFi" will let you also (once you connect a device to the Watchy via WiFi) "Update" the device with an OTA image file.

**Comment by KostasDaskalos** [comment]
I found the references for the setDarkBorder and I ...think I fixed it ( by commenting them out... ). I am now using your code and I can not be more happier!
Thank you for the amazing code! Keep up the good work!

**Comment by GuruSR** [comment]
The border won't go dark if you set it to dark mode, you'll wind up with a white border all the time, the GxEPD2 files can be altered to give that and you can uncomment the setDarkBorder back and use it.

**Comment by KostasDaskalos** [comment]
Thank you for the extra info but it is not my intention to use the dark mode anyway! But I will try to modify the code!
