### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by n3zf0r** [GuruSR/Watchy_GSR#3]
I am having a hard time installing this code into the watch, I was able to modify the necessary files in order to get the black border, but I keep getting compiling errors, not sure where I am going wrong, any chance you can help me? I currently running official watchy firmware.

My questions are:
 
On Arduino, what options do I choose and how do I actually load your code into it.

Where am I putting the extra files you mentioned (smallNTP ect...) 

I am a dummy I just need a step-by-step guide on how to do this, any help would greatly be appreciated.

**Comment by GuruSR** [comment]
The libraries you can download and place in either the same folder with the Watchy GSR or you can actually (if you're using Arduino), there should be an option to download the entire thing as a zip file, you can use the Library Manager to add it in manually for each.

I would recommend going to:  https://watchy.sqfmi.com/docs/faqs#i-have-another-issue-could-you-help-me-out   and click on the Discord link there to join the Watchy discord, I am on there from time to time, it would be easier to help there.

**Comment by n3zf0r** [comment]
> The libraries you can download and place in either the same folder with the Watchy GSR or you can actually (if you're using Arduino), there should be an option to download the entire thing as a zip file, you can use the Library Manager to add it in manually for each.
> 
> I would recommend going to: https://watchy.sqfmi.com/docs/faqs#i-have-another-issue-could-you-help-me-out and click on the Discord link there to join the Watchy discord, I am on there from time to time, it would be easier to help there.

Thank you, will look for you on Discord.
