### ISSUE TITLE
NOTES are confusing

### ISSUE THREAD

**Issue by egnor** [GuruSR/Watchy_GSR#4]
README.md includes this text

> Watchy uses version 1.0.6 or 2.0.2 (or higher than 2.0.3) of the ESP32 libraries, 2.0.0 won't compile, 2.0.2 causes a boot crash loop, remove them manually and revert back to version 1.0.6 or use 2.0.2 (which seems to have been fixed).

I think... one of those "2.0.2" references should be something else? If "2.0.2 causes a boot crash loop" then probably one shouldn't "use 2.0.2"?

**Comment by GuruSR** [comment]
Fixed, hopefully nobody else will get confused by that.
